### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by tbeu** [bsapundzhiev/bsxml-json#1]
I see in source files that some (like bsxml.c) are under GPL2 and some others (like bsstr.c) are not. expat itself is under MIT license. Since I want to use your code and expat in my FOSS application I need to know if I can use it. Preferable all your files would be under MIT or BSD3 license. Thanks.

**Comment by bsapundzhiev** [comment]
I recently added the LICENSE.txt file. I think GPLv2 is compatible with MIT so you can use whatever you want for your project.

**Comment by tbeu** [comment]
No, they are not compatible if I am not wrong. http://stackoverflow.com/questions/3902754/mit-vs-gpl-license

**Comment by dietmarw** [comment]
If your code is under MIT it can be included (and distributed) in GPL **and** MIT (and other licenses) projects. Whereas if it is under GPL you can only distribute it under GPL again. So having this project provided under MIT kind of renders the dual license option with GPL superfluous. So why over complicating things. Is there a specific use case that make you choose this dual license?

**Comment by bsapundzhiev** [comment]
Sorry, I'm not a software lawyer. I decide to use GPL because part of the code is from my other GPL project, so which license should i choose now GPL or MIT ?

**Comment by dietmarw** [comment]
MIT would be the simplest choice here allowing people to use it in GPL and MIT like projects to use it.

**Comment by bsapundzhiev** [comment]
Ok, I will change the license to MIT lather today it looks pretty simple and i hope to be useful.

**Comment by tbeu** [comment]
Thank you @bsapundzhiev  and @dietmarw !

**Comment by bsapundzhiev** [comment]
I found another GPL part bsstr.c which is modified version of https://github.com/hishamhm/dit/blob/master/StringBuffer.c so if I make change the license to MIT do I violate a GPL license  of 'dit' project ?

**Comment by tbeu** [comment]
I'd say yes, but best is you ask dit author for permission.

**Comment by dietmarw** [comment]
Unfortunately yes. If you are using any GPL code that you are not the author to, then you can only put your whole code under a compatible license. Which in this case means GPL v2 or later.
The only chance that you can license it to non-copyleft (e.g,. MIT; BSD) would be to ask the author if he can grant you a license other than GPL for your project.

**Comment by bsapundzhiev** [comment]
I think for now GPL v2 works for me and thanks for all clarifications.

**Comment by tbeu** [comment]
OK.
