### ISSUE TITLE
GPL again

### ISSUE THREAD

**Issue by tbeu** [bsapundzhiev/bsxml-json#12]
I needed to put my Modelica library [ExternData](https://github.com/tbeu/ExternData) under GPL 2 because it uses bsxml-json which is GPL 2 licensed.

All other libs I use in that project have a less restrictive license like BSD, MIT, Apache or even zlib.

I'd like to put ExternData under a less restrictive license (e.g. Simplified BSD) such that it can be used and distributed as closed source by commercial applications.

Do you think you can grant ExternData to publish bsxml-json under a different license? Please note that I made several small changes to bsxml-json which I did not send as pull request!

@dietmarw FYI

**Comment by bsapundzhiev** [comment]
The problem is well described in https://github.com/bsapundzhiev/bsxml-json/issues/1#issuecomment-97452823 
bsstr.c code is derivative work from 'dit' project, so i can grant you permission to change license except that piece of code. If LGPL works for you libconfig have similar implementation and can be added easily.

**Comment by tbeu** [comment]
:sweat: I think I need to rewrite bsstr.c using [utstring.h](https://github.com/troydhanson/uthash/blob/master/src/utstring.h) and array.c using [utarray.h](https://github.com/troydhanson/uthash/blob/master/src/utarray.h). Both headers are from [uthash](https://github.com/troydhanson/uthash) which already is used in ExternData.

**Comment by tbeu** [comment]
So if I remove bsstr from bsxml-json the license could be changed?

**Comment by bsapundzhiev** [comment]
Yes, do whatever you want

**Comment by tbeu** [comment]
Thank you!

Are you interested in the PR at all?

**Comment by bsapundzhiev** [comment]
The only thing i'm not interested is the license politic.

**Comment by tbeu** [comment]
Understandable.
