### ISSUE TITLE
Issues with JsonParser_stripCommentsFromBuffer

### ISSUE THREAD

**Issue by tbeu** [bsapundzhiev/bsxml-json#14]
1. It does not work for C++ line comments after quoted strings, i.e. in  line `"set1": { // First set` the comment is not deleted.
2. There is a potential out-of-range `buff` access in case `i` is `size-1`.
3. It won't work for escaped quotes, i.e. in line  `"set1": "First \"#set\""`

**Comment by bsapundzhiev** [comment]
Point 3 is a definitely a bug  in the parser

**Comment by bsapundzhiev** [comment]
Point 1 - only new line comments are supported for now

**Comment by tbeu** [comment]
> Point 1 - only new line comments are supported for now

It also works for lines like `{ // test.json`. Just the quote is the problem. I fixed it already in tbeu/ExternData@7176c413d6989b0b422c8d89e50824671ff54f10.

**Comment by tbeu** [comment]
Please note that tbeu/ExternData@7176c413d6989b0b422c8d89e50824671ff54f10 also fixes point 2 but not point 3.

**Comment by tbeu** [comment]
Thanks.

Wouldn't it be possible to ignore the line comments in the parser instead of additional function stripCommentsFromBuffer which is called beforehand?
