### ISSUE TITLE
Update array interface to use unsigned type for index

### ISSUE THREAD

**Issue by tbeu** [bsapundzhiev/bsxml-json#20]
What do you think about updating the array interface (struct and functions) to use an unsigned type for index and sizes, e.g., 
```c
typedef struct s_array {
    size_t num;
    size_t max;
    void *v;
    size_t elem_size;
} cpo_array_t;
```

**Comment by bsapundzhiev** [comment]
Good point, i cant remember why it's integer. Can you review https://github.com/bsapundzhiev/bsxml-json/tree/array-changes does it work for you.

**Comment by tbeu** [comment]
I fixed some more by a0db848970b1e05d60ea2a853aeec22831fec0d3 to round it off.

**Comment by tbeu** [comment]
Sorry, ed25b7bb580583de84049dadd90a8faf77785703 should fix these two GCC warnings, too.

**Comment by tbeu** [comment]
LGTM. Thanks.

**Comment by bsapundzhiev** [comment]
ff to master
