### ISSUE TITLE
cpo_array_get_at

### ISSUE THREAD

**Issue by tbeu** [bsapundzhiev/bsxml-json#22]
Some issues with cpo_array_get_at:
* The `index >= 0` within the `assert` can be skipped since `asize_t` is an unsigned type. This also holds for more checks in other functions.
* The `index <= a->num` within the `assert` should be changed to `index < a->num`.
* Should it return `NULL` in case `index >= a->num`?

**Comment by bsapundzhiev** [comment]
changes are [here](https://github.com/bsapundzhiev/bsxml-json/tree/array_changes) but need to be tested

**Comment by tbeu** [comment]
There are still some superfluous `a->num >= 0` assert checks in array.c.

**Comment by tbeu** [comment]
You now can even get rid of including `assert.h`.

**Comment by bsapundzhiev** [comment]
one more thing only heap allocated arrays should be resized with `cpo_array_setsize`

**Comment by tbeu** [comment]
I actually use `realloc` in `cpo_array_preallocate`
```c
static int cpo_array_preallocate(cpo_array_t *a, asize_t elements)
{
    void *newv;
    asize_t newmax = a->max;

    while (elements > newmax) {
        newmax = (newmax + 1) * 2;
    }

    newv = realloc(a->v, newmax * a->elem_size);

    if (newv == NULL)
        return -1;

    a->v = newv;
    a->max = newmax;
    return 0;
}
```
