### ISSUE TITLE
Support of JSON comments

### ISSUE THREAD

**Issue by tbeu** [bsapundzhiev/bsxml-json#5]
Although JSON does not officially support comments many libraries support C and C++ style comments.
Do you think you can add it, too?

See http://www.quora.com/How-do-I-write-comments-inside-a-JSON-document

**Comment by bsapundzhiev** [comment]
sure, it would be useful in config files. for fist time c++ comments are easy to implement

**Comment by tbeu** [comment]
Thanks, C++ line comments would really be nice to have.

**Comment by tbeu** [comment]
Do you think you can manage to add support for C++ line comments this week?

**Comment by bsapundzhiev** [comment]
I think it's not needed, you can strip comments when you read the data from the file just before passing it to the parser.

**Comment by tbeu** [comment]
This would mean double parsing, right? I use JsonParser_parseFile right now.

**Comment by bsapundzhiev** [comment]
Would you retest the issue with c++ and shell like comments ?

**Comment by tbeu** [comment]
Thanks. Both line comment styles work.
