### ISSUE TITLE
Fill m_errorString at parsing errors

### ISSUE THREAD

**Issue by tbeu** [bsapundzhiev/bsxml-json#8]
XmlParser_parse and XmlParser_parse_file should set m_errorString of XmlParser in case of error such that I can call XmlParser_getErrorString in my calling application to check for XML parsing errors. Can you please add it. Thanks!

**Comment by bsapundzhiev** [comment]
Thank you it was not implemented at all. Please retest with new changes, I hope it works

**Comment by tbeu** [comment]
Thanks for the fast reply. I do very appreciate it.

Can you please also fill the m_errorString in XmlParser_parse_file if fopen fails. Thanks.

And, actually having it also in JsonParser_parse and JsonParser_parseFile would also be very helpful for me. Thanks again!

**Comment by bsapundzhiev** [comment]
I made the requested changes. Also, fixed bug in json comment strip code.

**Comment by tbeu** [comment]
Thanks. Tiny correction: parser->m_errorString needs to be set to NULL in JsonParser_parse (similar as in XmlParser_parse).
